
modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
# A URL to refer people to when problems occur with this mod
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
# The modid of the mod
modId="littleadditions" #mandatory
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
# ${file.jarVersion} will substitute the value of the Implementation-Version as read from the mod's JAR file metadata
# see the associated build.gradle script for how to populate this completely automatically during a build
version="1.18.2-1.0" #mandatory
 # A display name for the mod
displayName="Little Additions" #mandatory
# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="https://www.curseforge.com/minecraft/mc-mods/littleadditions"
# A file name (in the root of the mod JAR) containing a logo for display
logoFile="LITTLE-ADDITIONS.png" #optional
# A text field displayed in the mod UI
credits="Thanks to the teachings of TurtyWurty and KaupenJoe I'm able to create this mod" #optional
# A text field displayed in the mod UI
authors="TheRealDoomSlayer69(goofyahhcreature69 in curseforge)" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
This is a vanilla friendly mod which adds many unused features, and some new ones which a lot of people including me wanted to be added in the main game.
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.littleadditions]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[40,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.littleadditions]] #optional
modId="patchouli" #mandatory
mandatory=false #mandatory
versionRange="1.18.2-71.1" #mandatory
ordering="NONE"
side="BOTH"